# 1) Build stage
FROM node:18-alpine AS builder
WORKDIR /app

# Install deps & build
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# 2) Run stage
FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# Install only production deps
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile

# Copy the build output and static assets
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["yarn", "start"]
